# Generated by Django 3.0.2 on 2020-01-05 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(choices=[('r', '#d4002d'), ('g', '#76b82a'), ('t', '#00afcb'), ('y', '#f7a600'), ('o', '#ec6608'), ('v', '#af1280'), ('b', '#005ca9')])),
                ('picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('duration', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HabitRabbit.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('friends', models.ManyToManyField(related_name='_member_friends_+', to='HabitRabbit.Member')),
                ('profile_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HabitRabbit.ProfilePicture')),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('name', models.TextField()),
                ('interval', models.PositiveSmallIntegerField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HabitRabbit.Member')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HabitRabbit.Type')),
            ],
        ),
    ]
