# Generated by Django 3.0.2 on 2020-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(),
        ),
    ]
