# Generated by Django 3.0.2 on 2020-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HabitRabbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='helpful_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
