# Generated by Django 3.0.2 on 2020-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='helpful_link',
        ),
        migrations.AddField(
            model_name='type',
            name='helpful_links',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='color',
            field=models.TextField(choices=[('r', '#d4002d'), ('g', '#76b82a'), ('t', '#00afcb'), ('y', '#f7a600'), ('o', '#ec6608'), ('v', '#af1280'), ('b', '#005ca9'), ('k', '#000000')]),
        ),
    ]
