# Generated by Django 3.0.2 on 2020-01-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
