# Generated by Django 3.0.2 on 2020-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0002_auto_20200114_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='color',
            field=models.TextField(choices=[('r', '#d4002d'), ('g', '#76b82a'), ('t', '#00afcb'), ('y', '#f8ff2e'), ('o', '#ec6608'), ('v', '#673ab7'), ('b', '#3876cf'), ('w', '#c49052')], default='r'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
