# Generated by Django 3.0.2 on 2020-01-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0002_auto_20200110_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='helpful_links',
            field=models.URLField(null=True),
        ),
    ]
