# Generated by Django 3.0.2 on 2020-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0002_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.TextField(),
        ),
    ]
