# Generated by Django 3.0.2 on 2020-01-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0003_auto_20200113_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='helpful_links',
            new_name='helpful_link',
        ),
    ]
