#  0005_merge_20200120_1616.py Copyright ©️ 2020 by the HabitRabbit developers (ardianq, lachchri16, sweiland, YellowIcicle).

# Generated by Django 3.0.2 on 2020-01-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0004_auto_20200120_1229'),
        ('HabitRabbit', '0004_auto_20200120_1145'),
    ]

    operations = [
    ]
