#  0007_habit_last_click.py Copyright ©️ 2020 by the HabitRabbit developers (ardianq, lachchri16, sweiland, YellowIcicle).

# Generated by Django 3.0.2 on 2020-01-20 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0006_user_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_click',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
