#  0009_auto_20200120_1646.py Copyright ©️ 2020 by the HabitRabbit developers (ardianq, lachchri16, sweiland, YellowIcicle).

# Generated by Django 3.0.2 on 2020-01-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0008_auto_20200120_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
