#  0010_auto_20200120_1647.py Copyright ©️ 2020 by the HabitRabbit developers (ardianq, lachchri16, sweiland, YellowIcicle).

# Generated by Django 3.0.2 on 2020-01-20 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0009_auto_20200120_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_click',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
