# Generated by Django 3.0.2 on 2020-01-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0003_auto_20200120_1608'),
        ('HabitRabbit', '0011_auto_20200120_1648'),
    ]

    operations = [
    ]
