# Generated by Django 3.0.2 on 2020-01-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0013_auto_20200121_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
