# Generated by Django 3.0.2 on 2020-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0014_habit_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='clicked',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
