#  0016_auto_20200123_1042.py Copyright ©️ 2020 by the HabitRabbit developers (ardianq, lachchri16, sweiland, YellowIcicle).

# Generated by Django 3.0.2 on 2020-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HabitRabbit', '0015_habit_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='clicked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
